# Generated by Django 5.1.4 on 2025-01-29 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_short', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('observations', models.TextField(null=True, blank=True)),
                ('photo', models.ImageField(upload_to='uploads/')),
                ('owned', models.IntegerField()),
                ('total_books', models.IntegerField(default=0)),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_spend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.origin')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.status')),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.language')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.type')),
            ],
        ),
    ]

